# Generated by Django 2.2 on 2020-10-19 05:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20201019_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profilel',
            new_name='Profile',
        ),
        migrations.RenameModel(
            old_name='Programsl',
            new_name='Programs',
        ),
        migrations.RenameModel(
            old_name='Programs_categoryl',
            new_name='Programs_category',
        ),
    ]
