# Generated by Django 2.2 on 2020-11-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201019_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resgister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=1000)),
                ('Program_name', models.CharField(max_length=1000)),
                ('Price', models.CharField(max_length=1000)),
                ('StartingDate', models.DateField(max_length=1000)),
                ('EndingDate', models.DateField(max_length=1000)),
                ('StartingTime', models.TimeField()),
                ('EndingTime', models.TimeField()),
            ],
        ),
    ]
