# Generated by Django 2.2 on 2020-11-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_resgister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resgister',
            old_name='EndingDate',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='resgister',
            old_name='StartingDate',
            new_name='Tinme',
        ),
        migrations.RemoveField(
            model_name='resgister',
            name='EndingTime',
        ),
        migrations.RemoveField(
            model_name='resgister',
            name='StartingTime',
        ),
    ]
