# Generated by Django 2.2 on 2020-11-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201108_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resgister',
            old_name='Tinme',
            new_name='Time',
        ),
    ]
