# Generated by Django 2.2 on 2020-11-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201108_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resgister',
            name='Date',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='resgister',
            name='Time',
            field=models.CharField(max_length=1000),
        ),
    ]
