# Generated by Django 2.2 on 2020-11-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201108_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resgister',
            new_name='Register',
        ),
    ]
