# Generated by Django 2.2 on 2020-12-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201108_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('cancel', 'cancel')], default='Active', max_length=100),
        ),
    ]
